sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - ~/.npm
    - "node_modules"
node_js:
  - "8"
install:
  - npm i
script:
  - npm run lint
  - npm run test
  - npm run build
